config/routes.rb
Rails.application.routes.draw do

get 'sessions/create'

get 'sessions/new'

get 'sessions/destroy'

  root 'restaurants#index'

  get 'restaurants/:restaurant_id/reservations/viewall' => 'reservations#viewall', as: :viewall

  resources :users do
    resources :restaurants
  end
  resources :sessions,    only: [:new, :create, :destroy]

  resources :restaurants do
    resources :reservations
  end

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

  belongs_to :restaurant
  belongs_to :users

  validates :party_size, :time, :date, presence: true
  validates :party_size, numericality: {only_integer: true}
  validate  :available?

  def available?
    unless party_size > 0 && available_capacity(time) >= party_size
      errors.add(:party_size, 'exceeds capacity at this date and time. Please select an alternative and try again.')
    end
  end

  private

  def available_capacity(time)
    restaurant.capacity - reservations_at(time).sum(:party_size)
  end

  def reservations_at(time)
    Reservation.where(time: time.beginning_of_hour..time.end_of_hour)
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :users, through: :reservations
  has_many :reservations, dependent: :destroy

  belongs_to :owner, class_name: "User", inverse_of: :owned_restaurants

  validates :name, :address, :phone, :capacity, :opening_hours, :closing_hours, presence: true
  validates :capacity, numericality: {only_integer: true}

  def self.find_by_first_letter(letter)
    @show = where('name LIKE ?', "#{letter}%").order('name ASC')
 end

 # def self.search(search)
 #   if search
 #     find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
 #  #  else
 #  #    find(:all)
 #   end
 # end


def self.search(search)
  where("name LIKE ?", "%#{search}%")
  where("name LIKE ?", "%#{search}%")
end

  # def available?(party_size, time)
  #   party_size > 0 && available_capacity(time) >= party_size
  # end
  #
  # private
  #
  # def available_capacity(time)
  #   :capacity - reservations_at(time).sum(:party_size)
  # end
  #
  # def reservations_at(time)
  #   reservations.where(time: time.beginning_of_hour..time.end_of_hour)
  # end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :reservations
  has_many :restaurants, through: :reservations

  has_many :owned_restaurants, class_name: "Restaurant", inverse_of: :owner, foreign_key: :owner_id

  validates :name, :password_digest, presence: true
  validates :email, uniqueness: true
  validates :phone, numericality: {only_integer: true}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end


end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action do
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def index
    @reservations = Reservation.all
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def new
    @reservation = Reservation.new
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.restaurant = @restaurant
    @reservation.user_id = session[:user_id]

    if @reservation.save
      redirect_to [@restaurant, @reservation], :notice => 'Reservation created with success'
    else
      render :new
    end
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update_attributes(reservation_params)
      redirect_to restaurant_reservation_path(@restaurant, @reservation)
    else
      render :edit
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to restaurants_path
  end

  def viewall
    @reservations = @restaurant.reservations.all
  end

  private
  def reservation_params
    params.require(:reservation).permit(:user_id, :restaurant_id, :party_size, :date, :time, :comment)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action      :find_user
  skip_before_action :find_user, only: [:index, :show, :edit, :update, :destroy]

  def index
     @restaurants = Restaurant.all
    # @show = Restaurant.find_by_first_letter('a')
    # @restaurants = Restaurant.search(params[:search])
    if params[:search]
   @restaurants = Restaurant.search(params[:search]).order("created_at DESC")
 else
   @restaurants = Restaurant.all.order('created_at DESC')
 end

  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.owner_id = params[:user_id]
    if @restaurant.save
      redirect_to [@user, @restaurant]
    else
      render :new
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(restaurant_params)
      redirect_to restaurant_url(@restaurant), :notice => 'Restaurant created with success'
    else
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    owner = @restaurant.owner_id
    @reservations = @restaurant.reservations
    @reservations.destroy
    @restaurant.destroy
    redirect_to user_path(owner)
  end

  def owner_show_page
    @restaurant = Restaurant.find_by(@user)

  end

  def default_photo
    'image.jpg'
  end


  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone, :capacity, :opening_hours, :closing_hours, :website, :photo)
  end

  def find_user
    @user = User.find(params[:user_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to restaurants_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to restaurants_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to restaurants_url, notice: "Account sucessfully created!"
      else
        render "new"
      end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_edit_params)
      redirect_to user_url(@user)
    else
      render :edit
    end
  end

  def reservations
    @reservations = @user.reservations.all
  end

  private

  def user_params
      params.require(:user).permit(:name, :phone, :email, :password, :password_confirmation)
  end

  def user_edit_params
    params.require(:user).permit(:name, :phone, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<div id="container">
<head>
  <link href='http://fonts.googleapis.com/css?family=Bungee|Muli|Playfair+Display' rel='stylesheet' type='text/css'>
  <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <title>Seatyourself</title>
</head>
<body id="body">
  <div class = "menu-bar">
      <span id = "logo">
        <%= link_to image_tag("seatyourself-logo.png"), restaurants_path %>
      </span>
      <span class = "userinfo">
          <% if current_user %>
            <span id = "welcome-message"> Signed in as <%= link_to "#{current_user.name}", user_path(current_user) %></span> |
            <span id = "log-out-button"><%= link_to "Log out", session_path("current"), :method => :delete %></span>
          <% else %>
            <span id = "log-in-button"><%= link_to "Log In", new_session_path %></span> |
            <span id = "sign-up-button"><%= link_to "Sign Up", new_user_path %></span>
          <% end %>
      </span>
  </div>

  <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:alert] %>
    <p id="alert"><%= flash[:alert] %></p>
  <% end %>

  <%= yield %>

  <div class="footer">
    <div class="left">
      <p>T: 416-567-7890</p>
      <p>E: info@seatyourself.com</p>
    </div>
    <span class="center">
      <a href="http://www.facebook.com"><img src="http://www.fastforwardsim.com/images/Facebook_icon_grey.png" alt="Facebook"></a>
      <a href="http://www.instagram.com"><img src="http://www.lorigoldsteinbooks.com/wp-content/uploads/2013/06/instagram-grey-2-300x300-150x150.png" alt="Instagram"></a>
      <a href="http://www.twitter.com"><img src="https://dl.dropboxusercontent.com/u/80500150/twitter.png" alt="Twitter"></a>
    </span>
    <div class="right">
      <p>www.seatyourself.com</p>
      <p>Copyright SeatYourself 2016</p>
    </div>
  </div>
</body>
</div>
</html>

app/views/reservations/_form.html.erb
<%= form_for [@restaurant, @reservation] do |f| %>

<%if @reservation.errors.any? %>
  <div id="error explanation">
    <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

    <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <%end%>
    </ul>
  </div>
  <% end %>

  <div class ="field">
    <%= f.label :party_size %><br />
    <%= f.text_field :party_size %>
  </div>

  <div class ="field">
    <%= f.label :date %><br />
    <%= f.date_field :date %>
  </div>

  <div class ="field">
    <%=f.label :time %><br />
    <%=f.time_select :time, start_hour:@restaurant.opening_hours.hour , end_hour:@restaurant.closing_hours.hour , ampm: true, discard_minute: true %>
  </div>

  <div class ="field">
    <%=f.label :comment %><br />
    <%=f.text_area :comment %>
  </div>

  <div class="actions">
      <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Edit Your Reservation</h1>

<div class="reservation-form">
  <div class="field">
    <%= Restaurant.find(@reservation.restaurant_id).name %>
  </div>
<%= render 'form' %>
</div>

app/views/reservations/new.html.erb
<div class="restaurant-form">
<%= render 'form' %>
</div>

app/views/reservations/show.html.erb
<div class="reservation">
  <h1>Your Reservation Details</h2>
    <h4 id="reservation-info">
      Restaurant:</strong> <%= @restaurant.name %><br />
      Date: <%= @reservation.date %><br />
      Time: <%= @reservation.time.strftime('%I:%M %p')%><br />
      Party Size: <%= @reservation.party_size %><br />
      Comments: <%= @reservation.comment %><br />
    </h4>
  <div class="button" id="reservation-button">
    <%= link_to "Edit", edit_restaurant_reservation_path %>
    <%= link_to "Delete", restaurant_reservation_path, method: :delete, data: {confirm: "Are you sure you want to cancel your reservation? "} %>
    <%= link_to "Back to Restaurant", restaurant_path(@restaurant) %>
  </div>
</div>

<div class="padding">
</div>

app/views/reservations/viewall.html.erb
<div class="reservation-header">
<div class="show-image">
  <% if @restaurant.photo == "" %>
    <%= image_tag "image.jpg" %><br>
  <% else %>
    <%= image_tag @restaurant.photo %><br />
  <% end %>
    <h1>Reservations (Total: <%= @reservations.length %> )</h1>
  </div>
</div>

<div class="reservationlist">
  <% @reservations.each do |reservation| %>
  <div class="reservation">
    <p id="reservation-info">
      <% if reservation.user_id %>
       Name: <%= User.find(reservation.user_id).name %><br>
       Phone: <%= User.find(reservation.user_id).phone %><br>
       <% else %>
       Name: Not specified<br>
       Phone: Not provided<br>
       <% end %>
       Party Size: <%= reservation.party_size %><br>
       Date: <%= reservation.date %><br>
       Time: <%= reservation.time.strftime("%I %p") %><br>
       Special Requests: <%= reservation.comment %><br>
       <%= link_to "Cancel this reservation", "/restaurants/#{reservation.restaurant_id}/reservations/#{reservation.id}", method: :delete, data: {confirm: "Are you sure you want to cancel this reservation? This cannot be undone."} %><br>
    </p>
  </div>
    <br><br>
  <% end %>
</div>

app/views/restaurants/_form.html.erb
<%= form_for [@user, @restaurant] do |f| %>

<%if @restaurant.errors.any? %>
<div id="error explanation">
  <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

  <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <%end%>
  </ul>
</div>
<% end %>

  <%if @restaurant.errors.any? %>
  <div id="error explanation">
    <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

    <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <%end%>
    </ul>
  </div>
  <% end %>

  <div class ="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class ="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>

  <div class ="field">
    <%=f.label :phone %><br />
    <%=f.text_field :phone %>
  </div>

  <div class ="field">
    <%=f.label :capacity %><br />
    <%=f.number_field :capacity %>
  </div>

  <div class ="field">
    <%=f.label :opening_hours %><br />
    <%=f.time_select :opening_hours, ampm: true, discard_minute: true %>
  </div>

  <div class ="field">
    <%=f.label :closing_hours %><br />
    <%=f.time_select :closing_hours, ampm: true, discard_minute: true %>
  </div>

  <div class ="field">
    <%=f.label :website %><br />
    <%=f.text_field :website %>
  </div>

  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit <%= @restaurant.name %></h1>

<div class="restaurant-form">
<%= render 'form', restaurant: @restaurant %>

<div class="actions">
<%= link_to "Delete Restaurant", restaurant_path, method: :delete, data: {confirm: "Are you sure you want to delete this restaurant?" } %>
</div>

<div class="actions">
<%= link_to 'Back', restaurants_path %>
</div>

</div>

app/views/restaurants/index.html.erb
<div class= "mn_img_container">
  <div id = "main-image">
    <%= image_tag("pexel-breakfast.jpg") %>
    <div id = "image-text-header">Good friends. Good food. Good times.</div>
    <div id = "image-subtext">Make a Reservation.</div>
    <div class="search">
      <%= form_tag(restaurants_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search by Name" %>
        <span class="actions"><%= submit_tag "Search" %></span>
      <% end %>
    </div>
  </div>
</div>

<div class="list-container">
  <% @restaurants.each do |restaurant| %>
  <ul class="list-items">
    <li id="image">
      <% if restaurant.photo == "" %>
        <%= link_to image_tag('image.jpg'), restaurant_path(restaurant) %>
      <% else %>
        <%= link_to image_tag(restaurant.photo), restaurant_path(restaurant) %><br>
      <% end %>
    <li id="name"><h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2></li>
    <li id="address">
       <h4><%=image_tag "location_icon.png"%> <%= restaurant.address %></h4>
    </li>
  </ul>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<div class="restaurant-form">
<%= render 'form' %>
<div class="actions">
  <%= link_to 'Back', restaurants_path %>
</div>
</div>

app/views/restaurants/show.html.erb
<div class="show-image">
  <% if @restaurant.photo == "" %>
        <%= image_tag "image.jpg" %><br>
      <% else %>
        <%= image_tag @restaurant.photo %><br />
      <% end %>
  <h1><%= @restaurant.name %></h1>
  <div class="button"><%= link_to "Make a Reservation", new_restaurant_reservation_url(@restaurant) %></div>
</div>
<div class="info">
  <h4>Address: <%= @restaurant.address %></h4><br />
  <h4>Phone: <%= @restaurant.phone %></h4><br />
  <h4>Website: <%= @restaurant.website %></h4><br />
  <h4>Hours of Operation: <%= @restaurant.opening_hours.strftime("%I %p") %> - <%= @restaurant.closing_hours.strftime("%I %p") %></h4>
</div>

app/views/users/_form.html.erb
<body class="show-image">

<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.telephone_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirm Password"%>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

</body>

app/views/users/edit.html.erb
<h1>Edit Information</h1>
<div id="user-form">
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br/>
    <%= f.telephone_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>
  <div class="actions">
    <%= link_to 'Back', user_path(@user) %>
  </div>
</div>

app/views/users/new.html.erb
<body class="sign-up">
  <div class="sign-up-form">

    <div class ="header">Sign Up Today!</div>
    <%= render 'form' %>

  </div>
</body>

app/views/users/show.html.erb
    <%= image_tag "food-salad.jpg" %><br />
    <h1><%= @user.name %></h1>
    <div class="button"><%= link_to "Edit Profile", edit_user_path(@user) %>
  </div>
</div>


<div class="info">
  <h4>
    E-mail: <%= @user.email %><br />
    Phone: <%= @user.phone %><br />
  </h4>
</div>

<div class = "profile-title">Your Reservations</div>

<div class="reservationlist">
  <% @user.reservations.each do |reservation| %>
  <div class="reservation">
    <p id="reservation-info">
       Restaurant: <%= Restaurant.find(reservation.restaurant_id).name %><br>
       Party Size: <%= reservation.party_size %><br>
       Date: <%= reservation.date %><br>
       Time: <%= reservation.time.strftime("%I %p") %><br>
       Special Requests: <%= reservation.comment %><br>
       <div class="button">
         <%= link_to "Edit", "/restaurants/#{reservation.restaurant_id}/reservations/#{reservation.id}/edit" %>
         <%= link_to "Delete", "/restaurants/#{reservation.restaurant_id}/reservations/#{reservation.id}", method: :delete, data: {confirm: "Are you sure you want to cancel your reservation? "} %>
       </div>
    </p>
  </div>
  <br><br>
  <% end %>
</div>

<div class = "profile-title">Your Restaurants</div>
<div class="button" id="new-restaurant">
  <%= link_to "Create a new restaurant", new_user_restaurant_path(@user) %>
</div>

<div class="restaurantlist">
  <% @user.owned_restaurants.each do |restaurant| %>
  <div class="restaurant">
    <div id="restaurant-info">
      <h2><%= restaurant.name %></h2>
      <div class="button" id="owner-function">
        <%= link_to "View Restaurant Details", restaurant_path(restaurant) %>
        <%= link_to "View All Reservations", viewall_path(restaurant) %>
        <%= link_to 'Edit Information', edit_restaurant_path(restaurant) %>
      </div>
    </div>
  </div>
  <br><br>
  <% end %>